TIME_TABLE = {
  "Adam": {
    "Monday": "9 AM – 3 PM",
    "Tuesday": "Off",
    "Wednesday": "3 PM – 9 PM",
    "Thursday": "9 AM – 3 PM",
    "Friday": "Off",
    "Saturday": "3 PM – 9 PM",
    "Sunday": "10 AM – 6 PM",
    "Services Offered": ["Massage session", "Total Body Stretch Session"]
  },
  "Anabella": {
    "Monday": "Off",
    "Tuesday": "9 AM – 3 PM",
    "Wednesday": "Off",
    "Thursday": "3 PM – 9 PM",
    "Friday": "9 AM – 3 PM",
    "Saturday": "Off",
    "Sunday": "10 AM – 6 PM",
    "Services Offered": ["Customized Facial", "Chemical Peel"]
  },
  "Carolin": {
    "Monday": "3 PM – 9 PM",
    "Tuesday": "Off",
    "Wednesday": "9 AM – 3 PM",
    "Thursday": "Off",
    "Friday": "3 PM – 9 PM",
    "Saturday": "9 AM – 3 PM",
    "Sunday": "Off",
    "Services Offered": ["Massage session", "Rapid Tension Relief session"]
  },
  "Celene": {
    "Monday": "9 AM – 3 PM",
    "Tuesday": "3 PM – 9 PM",
    "Wednesday": "Off",
    "Thursday": "9 AM – 3 PM",
    "Friday": "3 PM – 9 PM",
    "Saturday": "Off",
    "Sunday": "10 AM – 6 PM",
    "Services Offered": ["Microderm Infusion", "Oxygenating Treatment"]
  },
  "Asme": {
    "Monday": "Off",
    "Tuesday": "9 AM – 3 PM",
    "Wednesday": "3 PM – 9 PM",
    "Thursday": "Off",
    "Friday": "9 AM – 3 PM",
    "Saturday": "3 PM – 9 PM",
    "Sunday": "Off",
    "Services Offered": ["Massage session", "Total Body Stretch session"]
  },
  "Kendra": {
    "Monday": "3 PM – 9 PM",
    "Tuesday": "Off",
    "Wednesday": "9 AM – 3 PM",
    "Thursday": "3 PM – 9 PM",
    "Friday": "Off",
    "Saturday": "9 AM – 3 PM",
    "Sunday": "10 AM – 6 PM",
    "Services Offered": ["Rapid Tension Relief session", "Chemical Peel"]
  },
  "Kianni": {
    "Monday": "9 AM – 3 PM",
    "Tuesday": "3 PM – 9 PM",
    "Wednesday": "Off",
    "Thursday": "9 AM – 3 PM",
    "Friday": "3 PM – 9 PM",
    "Saturday": "Off",
    "Sunday": "10 AM – 6 PM",
    "Services Offered": ["Massage session", "Oxygenating Treatment"]
  },
  "Laly": {
    "Monday": "Off",
    "Tuesday": "9 AM – 3 PM",
    "Wednesday": "3 PM – 9 PM",
    "Thursday": "Off",
    "Friday": "9 AM – 3 PM",
    "Saturday": "3 PM – 9 PM",
    "Sunday": "Off",
    "Services Offered": ["Customized Facial", "Dermaplaning Treatment"]
  },
  "Ron": {
    "Monday": "3 PM – 9 PM",
    "Tuesday": "Off",
    "Wednesday": "9 AM – 3 PM",
    "Thursday": "3 PM – 9 PM",
    "Friday": "Off",
    "Saturday": "9 AM – 3 PM",
    "Sunday": "10 AM – 6 PM",
    "Services Offered": ["Massage session", "Rapid Tension Relief session"]
  },
  "Rosa": {
    "Monday": "9 AM – 3 PM",
    "Tuesday": "3 PM – 9 PM",
    "Wednesday": "Off",
    "Thursday": "9 AM – 3 PM",
    "Friday": "3 PM – 9 PM",
    "Saturday": "Off",
    "Sunday": "10 AM – 6 PM",
    "Services Offered": ["Total Body Stretch session", "Microderm Infusion"]
  },
  "Saniah": {
    "Monday": "Off",
    "Tuesday": "9 AM – 3 PM",
    "Wednesday": "3 PM – 9 PM",
    "Thursday": "Off",
    "Friday": "9 AM – 3 PM",
    "Saturday": "3 PM – 9 PM",
    "Sunday": "Off",
    "Services Offered": ["Chemical Peel", "Oxygenating Treatment"]
  },
  "Sigmund": {
    "Monday": "3 PM – 9 PM",
    "Tuesday": "Off",
    "Wednesday": "9 AM – 3 PM",
    "Thursday": "3 PM – 9 PM",
    "Friday": "Off",
    "Saturday": "9 AM – 3 PM",
    "Sunday": "10 AM – 6 PM",
    "Services Offered": ["Massage session", "Dermaplaning Treatment"]
  },
  "Venessa": {
    "Monday": "9 AM – 3 PM",
    "Tuesday": "3 PM – 9 PM",
    "Wednesday": "Off",
    "Thursday": "9 AM – 3 PM",
    "Friday": "3 PM – 9 PM",
    "Saturday": "Off",
    "Sunday": "10 AM – 6 PM",
    "Services Offered": ["Customized Facial", "Chemical Peel"]
  }
}

UPSALE_SERVICE = {'Chemical Peel': ['Service: Chemical Peel ==> Up Sale Services: Neck & Décolleté Treatment ==>Only pay more: $20 ==> Why should you try that: An enhancement extending facial benefits to the neck and décolleté helping reduce the appearance of lines and redness.',
  'Service: Chemical Peel ==> Up Sale Services: New! Exfoliating Neck & Décolleté Treatment ==>Only pay more: $30 ==> Why should you try that: An optional enhancement for a Chemical Exfoliation service, that extends the treatment area of the Chemical Exfoliation (face only) to include the neck and décolleté.',
  'Service: Chemical Peel ==> Up Sale Services: High Frequency ==>Only pay more: $15 ==> Why should you try that: A high frequency machine helps to cleanse your skin of pore clogging impurities.',
  'Service: Chemical Peel ==> Up Sale Services: Anti-Aging Eye Treatment ==>Only pay more: $15 ==> Why should you try that: Focuses on addressing fine lines, wrinkles and signs of aging around the delicate eye area.',
  'Service: Chemical Peel ==> Up Sale Services: Lip Treatment ==>Only pay more: $15 ==> Why should you try that: This three-step enhancement offers gentle exfoliation, nourishment, and hydration. Hyaluronic acid, peptides, and ceramides leave lips feeling soft and smooth, with a reduced appearance of expression lines and enhanced definition'],
 'Customized Facial': ['Service: Customized Facial ==> Up Sale Services: New! Cooling Globe Enhancement ==>Only pay more: $15 ==> Why should you try that: Transform your facial into an even more enjoyable sensory experience: add a gentle facial massage using chilled cooling globes.',
  'Service: Customized Facial ==> Up Sale Services: Neck & Décolleté Treatment ==>Only pay more: $20 ==> Why should you try that: An enhancement extending facial benefits to the neck and décolleté helping reduce the appearance of lines and redness.',
  'Service: Customized Facial ==> Up Sale Services: High Frequency ==>Only pay more: $15 ==> Why should you try that: A high frequency machine helps to cleanse your skin of pore clogging impurities.',
  'Service: Customized Facial ==> Up Sale Services: Anti-Aging Eye Treatment ==>Only pay more: $15 ==> Why should you try that: Focuses on addressing fine lines, wrinkles and signs of aging around the delicate eye area.',
  'Service: Customized Facial ==> Up Sale Services: Lip Treatment ==>Only pay more: $15 ==> Why should you try that: This three-step enhancement offers gentle exfoliation, nourishment, and hydration. Hyaluronic acid, peptides, and ceramides leave lips feeling soft and smooth, with a reduced appearance of expression lines and enhanced definition',
  'Service: Customized Facial ==> Up Sale Services: Exfoliating Hand Treatment ==>Only pay more: $15 ==> Why should you try that: Exfoliate and hydrate back of hands, arms and elbows that tend to show signs of dryness.',
  'Service: Customized Facial ==> Up Sale Services: Exfoliating Foot Treatment ==>Only pay more: $15 ==> Why should you try that: Soothe tired feet with exfoliating sugar scrub and moisturizing body butter.'],
 'Dermaplaning Treatment': ['Service: Dermaplaning Treatment ==> Up Sale Services: Neck & Décolleté Treatment ==>Only pay more: $20 ==> Why should you try that: An enhancement extending facial benefits to the neck and décolleté helping reduce the appearance of lines and redness.',
  'Service: Dermaplaning Treatment ==> Up Sale Services: New! Cooling Globe Enhancement ==>Only pay more: $20 ==> Why should you try that: An enhancement extending facial benefits to the neck and décolleté helping reduce the appearance of lines and redness.',
  'Service: Dermaplaning Treatment ==> Up Sale Services: High Frequency ==>Only pay more: $15 ==> Why should you try that: A high frequency machine helps to cleanse your skin of pore clogging impurities.',
  'Service: Dermaplaning Treatment ==> Up Sale Services: Anti-Aging Eye Treatment ==>Only pay more: $15 ==> Why should you try that: Focuses on addressing fine lines, wrinkles and signs of aging around the delicate eye area.',
  'Service: Dermaplaning Treatment ==> Up Sale Services: Lip Treatment ==>Only pay more: $15 ==> Why should you try that: This three-step enhancement offers gentle exfoliation, nourishment, and hydration. Hyaluronic acid, peptides, and ceramides leave lips feeling soft and smooth, with a reduced appearance of expression lines and enhanced definition',
  'Service: Dermaplaning Treatment ==> Up Sale Services: Exfoliating Hand Treatment ==>Only pay more: $15 ==> Why should you try that: Exfoliate and hydrate back of hands, arms and elbows that tend to show signs of dryness.',
  'Service: Dermaplaning Treatment ==> Up Sale Services: Exfoliating Foot Treatment ==>Only pay more: $15 ==> Why should you try that: Soothe tired feet with exfoliating sugar scrub and moisturizing body butter.'],
 'Massage Session': ['Service: Massage Session ==> Up Sale Services: Rapid Tension Relief ==>Only pay more: $15 ==> Why should you try that: A state-of-the-art massage device that employs vibration technology to help ease muscle tension.'],
 'Microderm Infusion': ['Service: Microderm Infusion ==> Up Sale Services: Neck & Décolleté Treatment ==>Only pay more: $20 ==> Why should you try that: An enhancement extending facial benefits to the neck and décolleté helping reduce the appearance of lines and redness.',
  'Service: Microderm Infusion ==> Up Sale Services: High Frequency ==>Only pay more: $15 ==> Why should you try that: A high frequency machine helps to cleanse your skin of pore clogging impurities.',
  'Service: Microderm Infusion ==> Up Sale Services: Anti-Aging Eye Treatment ==>Only pay more: $15 ==> Why should you try that: Focuses on addressing fine lines, wrinkles and signs of aging around the delicate eye area.',
  'Service: Microderm Infusion ==> Up Sale Services: Lip Treatment ==>Only pay more: $15 ==> Why should you try that: This three-step enhancement offers gentle exfoliation, nourishment, and hydration. Hyaluronic acid, peptides, and ceramides leave lips feeling soft and smooth, with a reduced appearance of expression lines and enhanced definition'],
 'Oxygenating Treatment': ['Service: Oxygenating Treatment ==> Up Sale Services: Neck & Décolleté Treatment ==>Only pay more: $20 ==> Why should you try that: An enhancement extending facial benefits to the neck and décolleté helping reduce the appearance of lines and redness.',
  'Service: Oxygenating Treatment ==> Up Sale Services: High Frequency ==>Only pay more: $15 ==> Why should you try that: A high frequency machine helps to cleanse your skin of pore clogging impurities.',
  'Service: Oxygenating Treatment ==> Up Sale Services: Anti-Aging Eye Treatment ==>Only pay more: $15 ==> Why should you try that: Focuses on addressing fine lines, wrinkles and signs of aging around the delicate eye area.',
  'Service: Oxygenating Treatment ==> Up Sale Services: Lip Treatment ==>Only pay more: $15 ==> Why should you try that: This three-step enhancement offers gentle exfoliation, nourishment, and hydration. Hyaluronic acid, peptides, and ceramides leave lips feeling soft and smooth, with a reduced appearance of expression lines and enhanced definition',
  'Service: Oxygenating Treatment ==> Up Sale Services: Exfoliating Hand Treatment ==>Only pay more: $15 ==> Why should you try that: Exfoliate and hydrate back of hands, arms and elbows that tend to show signs of dryness.',
  'Service: Oxygenating Treatment ==> Up Sale Services: Exfoliating Foot Treatment ==>Only pay more: $15 ==> Why should you try that: Soothe tired feet with exfoliating sugar scrub and moisturizing body butter.'],
 'Total Body Stretch Session': ['Service: Total body Stretch Session ==> Up Sale Services: Rapid Tension Relief ==>Only pay more: $15 ==> Why should you try that: A state-of-the-art massage device that employs vibration technology to help ease muscle tension.',
  'Service: Total body Stretch Session ==> Up Sale Services: New! Customized Cupping ==>Only pay more: $30 ==> Why should you try that: Cupping therapy works in harmony with your massage, promoting a relaxing and revitalizing experience.',
  'Service: Total body Stretch Session ==> Up Sale Services: Aromatherapy ==>Only pay more: $12 ==> Why should you try that: Relieve stress and inflammation or awaken the sense with essential oils extracted from herbs, fruits, and flowers',
  'Service: Total body Stretch Session ==> Up Sale Services: Aromatherapy - INVIGORATE ==>Only pay more: $12 ==> Why should you try that: Relieve stress and inflammation or awaken the sense with essential oils extracted from herbs, fruits, and flowers',
  'Service: Total body Stretch Session ==> Up Sale Services: Aromatherapy - RECHARGE ==>Only pay more: $12 ==> Why should you try that: Relieve stress and inflammation or awaken the sense with essential oils extracted from herbs, fruits, and flowers',
  'Service: Total body Stretch Session ==> Up Sale Services: Aromatherapy - RELAX ==>Only pay more: $12 ==> Why should you try that: Relieve stress and inflammation or awaken the sense with essential oils extracted from herbs, fruits, and flowers',
  'Service: Total body Stretch Session ==> Up Sale Services: Aromatherapy - SOOTHE ==>Only pay more: $12 ==> Why should you try that: Relieve stress and inflammation or awaken the sense with essential oils extracted from herbs, fruits, and flowers',
  'Service: Total body Stretch Session ==> Up Sale Services: Aromatherapy - UNWIND ==>Only pay more: $12 ==> Why should you try that: Relieve stress and inflammation or awaken the sense with essential oils extracted from herbs, fruits, and flowers',
  'Service: Total body Stretch Session ==> Up Sale Services: Enhanced Muscle Therapy ==>Only pay more: $15 ==> Why should you try that: Concentrated therapy using warming and cooling treatments to relieve deep muscle pain.',
  'Service: Total body Stretch Session ==> Up Sale Services: Hot Stone featuring thermabliss® ==>Only pay more: $30 ==> Why should you try that: Self-heating thermabliss® stones offer continuous, radiant warmth.',
  'Service: Total body Stretch Session ==> Up Sale Services: Exfoliating Foot Treatment ==>Only pay more: $15 ==> Why should you try that: Soothe tired feet with exfoliating sugar scrub and moisturizing body butter.',
  'Service: Total body Stretch Session ==> Up Sale Services: Exfoliating Hand Treatment ==>Only pay more: $15 ==> Why should you try that: Exfoliate and hydrate back of hands, arms and elbows that tend to show signs of dryness.']}

IMPROVE_TIME_TABLE = {'Chemical Peel': {'Anabella': {
   'Monday': 'Off',
   'Tuesday': '9 AM – 3 PM',
   'Wednesday': 'Off',
   'Thursday': '3 PM – 9 PM',
   'Friday': '9 AM – 3 PM',
   'Saturday': 'Off',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Chemical Peel'},
  'Kendra': {
   'Monday': '3 PM – 9 PM',
   'Tuesday': 'Off',
   'Wednesday': '9 AM – 3 PM',
   'Thursday': '3 PM – 9 PM',
   'Friday': 'Off',
   'Saturday': '9 AM – 3 PM',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Chemical Peel'},
  'Saniah': {
   'Monday': 'Off',
   'Tuesday': '9 AM – 3 PM',
   'Wednesday': '3 PM – 9 PM',
   'Thursday': 'Off',
   'Friday': '9 AM – 3 PM',
   'Saturday': '3 PM – 9 PM',
   'Sunday': 'Off',
   'Service': 'Chemical Peel'},
  'Venessa': {
   'Monday': '9 AM – 3 PM',
   'Tuesday': '3 PM – 9 PM',
   'Wednesday': 'Off',
   'Thursday': '9 AM – 3 PM',
   'Friday': '3 PM – 9 PM',
   'Saturday': 'Off',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Chemical Peel'}},
 'Customized Facial': {'Anabella': {
   'Monday': 'Off',
   'Tuesday': '9 AM – 3 PM',
   'Wednesday': 'Off',
   'Thursday': '3 PM – 9 PM',
   'Friday': '9 AM – 3 PM',
   'Saturday': 'Off',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Customized Facial'},
  'Laly': {
   'Monday': 'Off',
   'Tuesday': '9 AM – 3 PM',
   'Wednesday': '3 PM – 9 PM',
   'Thursday': 'Off',
   'Friday': '9 AM – 3 PM',
   'Saturday': '3 PM – 9 PM',
   'Sunday': 'Off',
   'Service': 'Customized Facial'},
  'Venessa': {
   'Monday': '9 AM – 3 PM',
   'Tuesday': '3 PM – 9 PM',
   'Wednesday': 'Off',
   'Thursday': '9 AM – 3 PM',
   'Friday': '3 PM – 9 PM',
   'Saturday': 'Off',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Customized Facial'}},
 'Dermaplaning Treatment': {'Laly': {
   'Monday': 'Off',
   'Tuesday': '9 AM – 3 PM',
   'Wednesday': '3 PM – 9 PM',
   'Thursday': 'Off',
   'Friday': '9 AM – 3 PM',
   'Saturday': '3 PM – 9 PM',
   'Sunday': 'Off',
   'Service': 'Dermaplaning Treatment'},
  'Sigmund': {
   'Monday': '3 PM – 9 PM',
   'Tuesday': 'Off',
   'Wednesday': '9 AM – 3 PM',
   'Thursday': '3 PM – 9 PM',
   'Friday': 'Off',
   'Saturday': '9 AM – 3 PM',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Dermaplaning Treatment'}},
 'Massage Session': {'Adam': {
   'Monday': '9 AM – 3 PM',
   'Tuesday': 'Off',
   'Wednesday': '3 PM – 9 PM',
   'Thursday': '9 AM – 3 PM',
   'Friday': 'Off',
   'Saturday': '3 PM – 9 PM',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Massage session'},
  'Carolin': {
   'Monday': '3 PM – 9 PM',
   'Tuesday': 'Off',
   'Wednesday': '9 AM – 3 PM',
   'Thursday': 'Off',
   'Friday': '3 PM – 9 PM',
   'Saturday': '9 AM – 3 PM',
   'Sunday': 'Off',
   'Service': 'Massage session'},
  'Asme': {
   'Monday': 'Off',
   'Tuesday': '9 AM – 3 PM',
   'Wednesday': '3 PM – 9 PM',
   'Thursday': 'Off',
   'Friday': '9 AM – 3 PM',
   'Saturday': '3 PM – 9 PM',
   'Sunday': 'Off',
   'Service': 'Massage session'},
  'Kianni': {
   'Monday': '9 AM – 3 PM',
   'Tuesday': '3 PM – 9 PM',
   'Wednesday': 'Off',
   'Thursday': '9 AM – 3 PM',
   'Friday': '3 PM – 9 PM',
   'Saturday': 'Off',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Massage session'},
  'Ron': {
   'Monday': '3 PM – 9 PM',
   'Tuesday': 'Off',
   'Wednesday': '9 AM – 3 PM',
   'Thursday': '3 PM – 9 PM',
   'Friday': 'Off',
   'Saturday': '9 AM – 3 PM',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Massage session'},
  'Sigmund': {
   'Monday': '3 PM – 9 PM',
   'Tuesday': 'Off',
   'Wednesday': '9 AM – 3 PM',
   'Thursday': '3 PM – 9 PM',
   'Friday': 'Off',
   'Saturday': '9 AM – 3 PM',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Massage session'}},
 'Microderm Infusion': {'Celene': {
   'Monday': '9 AM – 3 PM',
   'Tuesday': '3 PM – 9 PM',
   'Wednesday': 'Off',
   'Thursday': '9 AM – 3 PM',
   'Friday': '3 PM – 9 PM',
   'Saturday': 'Off',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Microderm Infusion'},
  'Rosa': {
   'Monday': '9 AM – 3 PM',
   'Tuesday': '3 PM – 9 PM',
   'Wednesday': 'Off',
   'Thursday': '9 AM – 3 PM',
   'Friday': '3 PM – 9 PM',
   'Saturday': 'Off',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Microderm Infusion'}},
 'Oxygenating Treatment': {'Celene': {
   'Monday': '9 AM – 3 PM',
   'Tuesday': '3 PM – 9 PM',
   'Wednesday': 'Off',
   'Thursday': '9 AM – 3 PM',
   'Friday': '3 PM – 9 PM',
   'Saturday': 'Off',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Oxygenating Treatment'},
  'Kianni': {
   'Monday': '9 AM – 3 PM',
   'Tuesday': '3 PM – 9 PM',
   'Wednesday': 'Off',
   'Thursday': '9 AM – 3 PM',
   'Friday': '3 PM – 9 PM',
   'Saturday': 'Off',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Oxygenating Treatment'},
  'Saniah': {
   'Monday': 'Off',
   'Tuesday': '9 AM – 3 PM',
   'Wednesday': '3 PM – 9 PM',
   'Thursday': 'Off',
   'Friday': '9 AM – 3 PM',
   'Saturday': '3 PM – 9 PM',
   'Sunday': 'Off',
   'Service': 'Oxygenating Treatment'}},
 'Rapid Tension Relief Session': {'Carolin': {
   'Monday': '3 PM – 9 PM',
   'Tuesday': 'Off',
   'Wednesday': '9 AM – 3 PM',
   'Thursday': 'Off',
   'Friday': '3 PM – 9 PM',
   'Saturday': '9 AM – 3 PM',
   'Sunday': 'Off',
   'Service': 'Rapid Tension Relief session'},
  'Kendra': {
   'Monday': '3 PM – 9 PM',
   'Tuesday': 'Off',
   'Wednesday': '9 AM – 3 PM',
   'Thursday': '3 PM – 9 PM',
   'Friday': 'Off',
   'Saturday': '9 AM – 3 PM',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Rapid Tension Relief session'},
  'Ron': {
   'Monday': '3 PM – 9 PM',
   'Tuesday': 'Off',
   'Wednesday': '9 AM – 3 PM',
   'Thursday': '3 PM – 9 PM',
   'Friday': 'Off',
   'Saturday': '9 AM – 3 PM',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Rapid Tension Relief session'}},
 'Total Body Stretch Session': {'Adam': {
   'Monday': '9 AM – 3 PM',
   'Tuesday': 'Off',
   'Wednesday': '3 PM – 9 PM',
   'Thursday': '9 AM – 3 PM',
   'Friday': 'Off',
   'Saturday': '3 PM – 9 PM',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Total Body Stretch session'},
  'Asme': {
   'Monday': 'Off',
   'Tuesday': '9 AM – 3 PM',
   'Wednesday': '3 PM – 9 PM',
   'Thursday': 'Off',
   'Friday': '9 AM – 3 PM',
   'Saturday': '3 PM – 9 PM',
   'Sunday': 'Off',
   'Service': 'Total Body Stretch session'},
  'Rosa': {
   'Monday': '9 AM – 3 PM',
   'Tuesday': '3 PM – 9 PM',
   'Wednesday': 'Off',
   'Thursday': '9 AM – 3 PM',
   'Friday': '3 PM – 9 PM',
   'Saturday': 'Off',
   'Sunday': '10 AM – 6 PM',
   'Service': 'Total Body Stretch session'}}}